import Head from "next/head";
import { useState } from "react";
import { Inter } from "@next/font/google";
import { IoLogoTumblr } from "react-icons/io";
import { IoLogoTwitter } from "react-icons/io";
import { IoLogoYoutube } from "react-icons/io";
import { IoLogoSkype } from "react-icons/io";
import { IoIosCloseCircle } from "react-icons/io";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [todoList, setTodoList] = useState([]);
  const [getValueText, setGetValueText] = useState("");

  //get the value of input
  const getValueFromInput = (e) => {
    setGetValueText(e.target.value);
  };

  //combine the value of input to an object
  const combined = () => {
    const stringToObject = {
      id: todoList.length === 0 ? todoList.length + 1 : todoList.length + 1,
      todoName: getValueText,
      isCompleted: false,
    };

    setTodoList([...todoList, stringToObject]);
  };

  //delete the list 

  const deleteTodo = (id) => {

    const getTodoList = todoList.filter((todo) => {
     return todo.id !== id
    })

    setTodoList(getTodoList)

  }

//Complete the TODO
  const completeTodoList = (id) => {

    setTodoList(todoList.map((todo) => {
      if (todo.id === id) {
        return {...todo, isCompleted: true}
      } else {
        return todo
      }
    }))
  }

  // INCOMPLETE THE TODO
  const inCompleteTodoList = (id) => {
    setTodoList(todoList.map((todo) => {
      if (todo.id === id) {
        return {...todo, isCompleted: false}
      } else {
        return todo
      }
    }))
  }

  console.log(todoList)

  return (
    <>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <header>
          <h1 className="text-4xl font-bold text-center p-8 bg-gradient-to-r from-cyan-400 to-blue-600 white">
            Todo App
          </h1>
        </header>

        <section className="h-[75vh]">
          <div className="mt-16 px-4">
            <div className="flex justify-center">
              <input
                type="text"
                placeholder="Type text here"
                className=" border-2 py-1 px-4"
                onChange={getValueFromInput}
              />
              <button
                onClick={combined}
                className="font-bold rounded-sm py-1 px-6 border-2 border-blue-300 bg-gradient-to-r from-cyan-400 to-blue-600 white text-transparent bg-clip-text hover:bg-clip-border hover:text-white transition-all duration-900 ease-in-out"
              >
                Add Todo
              </button>
            </div>

            <div className="flex flex-col space-y-2 mt-12 overflow-auto max-h-[50vh] border p-16">
              <h3 className="text-2xl text-center">List of Todos</h3>

              {/* LOOP THE LIST */}
              {todoList.map((todo, key) => {
                return (
                  <div key={key} className="flex gap-2 items-center justify-center pt-4">
                    <p className={todo.isCompleted ? "font-bold line-through" : "font-bold" }>{ todo.todoName }</p>
                    <button onClick={()=> completeTodoList(todo.id)} className="border py-1 px-4 bg-green-300 rounded-sm hover:bg-black hover:text-white transition-all duration-300 ease-in-out">
                      Completed
                    </button>
                    <button onClick={()=> inCompleteTodoList(todo.id)} className="border py-1 px-4 bg-blue-300 rounded-sm hover:bg-black hover:text-white transition-all duration-300 ease ease-in-out">
                      Incomplete
                    </button>

                    <button onClick={() => deleteTodo(todo.id)}>
                      <IoIosCloseCircle className="w-6 h-6 text-red-500 hover:text-red-300 transition-all duration-300 ease-in-out" />
                    </button>
                    
                  </div>
                );
              })}
            </div>
          </div>
        </section>

        <footer>
          <div className="bg-black p-6 flex items-center justify-center gap-4">
            <h3 className="text-white">
              Developed by: DeyvTech &copy; {new Date().getFullYear()}{" "}
            </h3>
            <div className="flex gap-1">
              <IoLogoTumblr className="text-blue-300 w-5 h-5" />
              <IoLogoTwitter className="text-blue-300 w-5 h-5" />
              <IoLogoYoutube className="text-blue-300 w-5 h-5" />
              <IoLogoSkype className="text-blue-300 w-5 h-5" />
            </div>
          </div>
        </footer>
      </main>
    </>
  );
}
